### ISSUE TITLE
Attempting to enchant boots causes crash

### ISSUE THREAD

**Issue by katubug** [MincraftEinstein/UsefulSlime#1]
Hi! I wanted to enchant my slime boots with a book, but on attempting to place them in the first Anvil slot, it crashes my game. 

MC 1.19.2
Forge 43.2.3

[crash-2023-02-12_11.57.05-client.txt](https://github.com/MincraftEinstein/UsefulSlime/files/10716811/crash-2023-02-12_11.57.05-client.txt)

**Comment by MincraftEinstein** [comment]
A version has been released on Curseforge to hopefully fix this
