### ISSUE TITLE
[1.20.1] Is there any way to make the mod compatible with neoforge again?

### ISSUE THREAD

**Issue by Zedrimar** [MincraftEinstein/UsefulSlime#11]
I forgot to submit this earlier, but the latest version of the mod got forge bumped and now no longer works with neoforge. Is there any way to have it compatible with neoforge again?

If there is any way to have it compatible with neoforge again, that would be awesome!

Not sure if it helps, but the mod version in question is 1.8.1 for 1.20.1

**Comment by MincraftEinstein** [comment]
Yes as far as I know it is fully possible to do it, I just have to create a dedicated port for it, which I haven't gotten around to doing, but hopefully soon

**Comment by Zedrimar** [comment]
Ah ok cool, thank you! :)
