### ISSUE TITLE
Hyperspeed Sling in water

### ISSUE THREAD

**Issue by MoonstruckDev** [MincraftEinstein/UsefulSlime#12]
## Client Information 

- Forge 47.2.30
- Minecraft 1.20.1 
- Mod Version 1.8.1

## Description

When you are blessed with Dolphins grace and you use the sling in water, you will go hyperspeed. This by itself doesn't sound too bad until you realize that loading this many chunks THIS quick crashes servers and certain hardware.

Also, even after initial hyperspeed when you move in water the bug still persists

I have attached a video so you can see. This is JUST with Useful Slime mod and Common network

https://youtu.be/fEwVM0zUYhA

**Comment by MincraftEinstein** [comment]
Thank you for reporting the issue and providing a video. I'll get to work on it soon
