### ISSUE TITLE
Sling Hypersprint

### ISSUE THREAD

**Issue by MoonstruckDev** [MincraftEinstein/UsefulSlime#13]
Hi! Me again! 

Minecraft Version: 1.20.1
Forge Version: 47.2.30
Mod Version: 1.8.1

After you use slime sling sprinting is faster than usual

You can see normal sprint speed at the start of the clip, then you can see post sling
[Video here](https://youtu.be/7SYgxQWtjcQ)

**Comment by MincraftEinstein** [comment]
Hi. Sorry to take so long to respond I have been sick the last few days. I released a mod version for 1.20.2 after your last issue that fixes this issue, unfortunately, I won't be backporting to 1.20.1 due to some dependency issues. Thank you for reporting the bug though.
