### ISSUE TITLE
Slime boots and sling not enchantable? MC 1.21 Fabric

### ISSUE THREAD

**Issue by Knito58** [MincraftEinstein/UsefulSlime#16]
As my slime boots decay to fast I wanted to put "mending" and "unbreakable" on them. But no.
The sling also resists.

Is that the intended way it should work?

What I tried: books in anvil and throwing it into the enchantment table.
The table seems to work partly. I can see enchantment rows turning light but they are not deciphered and clicking on them has no reaction.

No crash! That is good.

**Comment by MincraftEinstein** [comment]
No that's not intended behavior, I will fix it soon. Thanks reporting this
