### ISSUE TITLE
holding shift on a slippery slime lags out the server and client

### ISSUE THREAD

**Issue by yolomab** [MincraftEinstein/UsefulSlime#8]
theres not much else to add its easily repeatable
instructions:
place slippery slime
hold shift on the block so you dont fall off
the game then lags extremely hard, sometimes teleporting you millions of blocks away and other times crashing the server

**Comment by MincraftEinstein** [comment]
Thanks for reporting the issue! I don't know what to say about this, seeing as I didn't change anything for the Slippery Slime Block between 1.19 and 1.20. I'll try to fix it, but if I can't, it might be time to say goodbye to the Slippery Slime Block
