### ISSUE TITLE
Game crashing with UsefulSlime.

### ISSUE THREAD

**Issue by iLoveeAnime** [MincraftEinstein/UsefulSlime#9]
Minecraft launcher: Feather
Version: 1.20.1

I tried it on curseforge aswell but It crashes with Exit Code 1 in curseforge.
[message.txt](https://github.com/MincraftEinstein/UsefulSlime/files/12774427/message.txt)

**Comment by MincraftEinstein** [comment]
I have released a patch that should fix this. Let me know if it doesn't
